-- Mock row: 2026-04-17 AMS–DOH QR274 with planned + tail data (Qsuite match).
-- Run: npm run db:seed-mock   (requires DATABASE_URL)
INSERT INTO "DailyCompare" (
  "id",
  "compareDate",
  "flight",
  "routeKey",
  "plannedEquipment",
  "plannedQsuiteApi",
  "plannedQueryDate",
  "plannedDepartureLocal",
  "actualRegistration",
  "actualAircraftCell",
  "actualEquipment",
  "actualQsuiteFromTail",
  "matchQsuite",
  "matchEquipment",
  "fr24Error",
  "source",
  "createdAt",
  "updatedAt"
) VALUES (
  'seed_mock_qr274_20260417',
  DATE '2026-04-17',
  'QR274',
  'AMS-DOH',
  'A350-900',
  true,
  '2026-04-17',
  '2026-04-17T16:40:00',
  'A7-AMG',
  'Airbus A350-900',
  'A350-900',
  true,
  true,
  true,
  NULL,
  'mock',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
)
ON CONFLICT ("compareDate", "flight", "routeKey") DO UPDATE SET
  "plannedEquipment" = EXCLUDED."plannedEquipment",
  "plannedQsuiteApi" = EXCLUDED."plannedQsuiteApi",
  "plannedQueryDate" = EXCLUDED."plannedQueryDate",
  "plannedDepartureLocal" = EXCLUDED."plannedDepartureLocal",
  "actualRegistration" = EXCLUDED."actualRegistration",
  "actualAircraftCell" = EXCLUDED."actualAircraftCell",
  "actualEquipment" = EXCLUDED."actualEquipment",
  "actualQsuiteFromTail" = EXCLUDED."actualQsuiteFromTail",
  "matchQsuite" = EXCLUDED."matchQsuite",
  "matchEquipment" = EXCLUDED."matchEquipment",
  "fr24Error" = EXCLUDED."fr24Error",
  "source" = EXCLUDED."source",
  "updatedAt" = CURRENT_TIMESTAMP;
